# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.capstone
            source ~/.capstone/bin/activate
            make install
            
      - run:
          name: run lint
          command: |
            source ~/.capstone/bin/activate
            make lint
  
          no_output_timeout: 30m 
  
workflows:
  deployment:
    jobs:
      - lint

