apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue2
  labels:
    app: blue2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue2
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blue2
    spec:
      containers:
        - image: gauravkr04/udacityblue:latest
          imagePullPolicy: Always
          name: blue2
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: blue2
  labels:
    app: blue2
spec:
  type: LoadBalancer
  selector:
    app: blue2
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP